kinyarwanda:
  muraho: "Muraho, murakomeye?"
  amakuru: "Ni meza, ayanyu se?!"
  witwa nde: "Nitwa Keza Kamaliza."
  ukora iki: "Ndi umuganga ku bitaro by'akarere"
  uvuye he: "Nari ndi hano ntahantu nagiye."